### ISSUE TITLE
App redirects to Notifications > Comments after loosing focus

### ISSUE THREAD

**Issue by codinghusi** [forem/DEV-Android#125]
(A bug on the Android App, is this the right place for it?)

**Describe the bug**
When the app loses focus, it redirects me always to Notifications > Comments.
That behaviour is very nerve wrecking when I just shortly answer a chat or check a translation while writing an article (as I'm not native english)

**To Reproduce**
1. Go to whatever Home, Listing or any other
2. Loose Focus: Press Home button / switch apps
3. You get redirected to Notifications > Comments

**Expected behavior**
Just stay where I was

**Smartphone (please complete the following information):**
- Device: Samsung A5 (2017)
- OS, version: Android 8.0

**Comment by codinghusi** [comment]
Oh nice, that fixed it for me, too!
Didn't think that this could fix the issue, thanks a lot :)

**Comment by rt4914** [comment]
Closing this as it is not required now.
