### ISSUE TITLE
Dev App for Windows

### ISSUE THREAD

**Issue by steskalja** [forem/DEV-Android#127]
With the idea of creating native webview apps for Dev. Will there be a Windows 10 app coming out? I no longer see dev.to as an installable pwa.

**Comment by fdoxyz** [comment]
Hello @steskalja, we indeed chose to remove the PWA features from all Forems (DEV included) for the moment. 

For a bit of context on the topic, we do want to bring it back but in a slightly different form. We don't have a set timeframe for this at the moment though. If you're strongly interested in this feature we welcome everyone to start conversations about feature requests in _forem.dev_ ([more details in this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4)).

**Comment by rt4914** [comment]
Closing this as it is not required now.
