### ISSUE TITLE
Possible Issue with Nav Bar on Some Mobile Phones

### ISSUE THREAD

**Issue by michael-tharrington** [forem/DEV-Android#130]
**Describe the bug**

For some users, the top nav bar (bar with search, notifications, chat, etc.) isn't sticky on mobile. That said, this isn't the case for all users.

**Expected behavior**

The top nav bar should be sticky and visible to all.

**Screenshots**

Here are some screenshots that a DEV user give me permission to share:

![Screenshot_20210529-172700_2](https://user-images.githubusercontent.com/16007075/120358951-1caf3880-c2d5-11eb-9171-e6f60f931c8b.png)

![Screenshot_20210529-172715_2](https://user-images.githubusercontent.com/16007075/120358962-1faa2900-c2d5-11eb-81f3-77caafcaff99.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 6 TA-1021
 - OS: android 9
 - Version: version 1.5.0 - 2

**Additional context**

Strangely, I wasn't able to recreate this on my phone — granted I have Android version 11 and am running a Pixel 4a. @ellativity  also wasn't facing this issue and runs Nokia 6.1 Android 10 on the same app version.

If this could be solved by the user updating their OS, then just let me know!

**Comment by rt4914** [comment]
Fixed in web. Closing this as it is not required now.
