### ISSUE TITLE
Issue with dark mode DEV logo

### ISSUE THREAD

**Issue by FounderCasey** [forem/DEV-Android#136]
**Describe the bug**

A DEV user reached out to us on Discord with a bug that is not displaying the DEV logo properly while on dark mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/19507316/142049902-053ded7e-14c4-44d5-9f4d-00fcb4d45154.png)

**Smartphone (please complete the following information):**
 - Device: Android Device
 - OS: Unkown
 - Version: 1.5.0 - 2

**Comment by xtanion** [comment]
As from the screenshots it seem like a MIUI based device, It simply reverts the color of UI (even SVG images).

**Comment by rt4914** [comment]
Closing this as it is not required now.
