### ISSUE TITLE
Broken link on README / DEV Community app vs. Forem app question

### ISSUE THREAD

**Issue by bpires** [forem/DEV-Android#150]
The “Get it on Google Play” button on README.md leads to a broken URL. 

Couldn't find DEV Community Android App by searching directly on the Play Store either.

I have been using the Forem Android App to access DEV.to. Is it safe to assume that the stand-alone android app has been deprecated in favour of the Forem App? If this is the case, it would be better to provide some clarification in the readme.

Interestingly, the DEV Community iOS App seems to be still available on the App Store, so that left me curious.

**Comment by rt4914** [comment]
Closing this as it is not required now.
