### ISSUE TITLE
Option to change text size

### ISSUE THREAD

**Issue by TimS-** [forem/DEV-Android#23]
Sometimes I find the text size on the Android app a little small, depending on where I am and what I'm doing.

It'd be great if there were an option to adjust the text size, either directly from the reading pane or within the app settings, as changing my system wide settings in Android is not ideal.

**Comment by Pheonix73** [comment]
@maestromac is this currently been worked on?

**Comment by nizarmah** [comment]
Wouldn't this issue be better implemented on the web app?

**Comment by rt4914** [comment]
Closing this issue as it can be covered correctly only when we plan to create app natively. We don't need to keep this separate issue open.
