### ISSUE TITLE
Error URL does not exist when trying to save articles

### ISSUE THREAD

**Issue by ghost** [forem/DEV-Android#37]
**Describe the bug**

I keep getting the error about URL does not exist when trying to save posts - please see attached screenshot. It was using the DEV app on Android.

**To Reproduce**
Log into account via mobile app.
Click on edit for one of your articles
Click on save
The error appeared

NOTE! This error only was raised when trying to save some articles but not all of them so I cannot tell what the cause is or how to reliably reproduce the issue.

**Expected behavior**

You should click on save and it doesn't show the error and it successfully updated the article.

**Screenshots**

![Screenshot_20190608-123303_DEV   Community](https://user-images.githubusercontent.com/22416807/59353353-aea18d80-8d1a-11e9-9586-652d6d8b6f56.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung A50
 - OS: Android 9
 - Version 9

**Additional context**

**Comment by ryanwhocodes** [comment]
![Screenshot_20190608-123303_DEV   Community](https://user-images.githubusercontent.com/22416807/59352932-c75d7380-8d19-11e9-9216-6a605d8c8a81.jpg)

Above is a screenshot of the error

**Comment by ryanwhocodes** [comment]
Apologies, was trying to add the screenshot via desktop view on a mobile phone screen and accidentally closed the issue, reopened it again now.

**Comment by maestromac** [comment]
That's alright @ryanwhocodes . Can you share a complete raw markdown for this?

**Comment by ryanwhocodes** [comment]
No sorry, I ended up deleting this in the end. If nobody else has this issue then I don't mind closing it. The error was a bit cryptic, eg I didn't know which line in the markdown file may have caused it or whether something was happening elsewhere in the code operations...

**Comment by maestromac** [comment]
All good. We can keep this open in case anybody else run into it, then let stale-bot take care of it when the time comes.

**Comment by Tanjaddaniel** [comment]
For this issue, you only need to contact a https:/www.xgeeksquad.com/geek-squad-total-tech-support/ - **Geek Squad Total Tech Support Number +1(888)383-7303** operates smoothly to serve customers and has a broad range of solutions to problems, our **Geek Squad Support** offers you with all the responses to your problems.

**Comment by rt4914** [comment]
Looks like no was faced this issue. Lets deprecate this issue.
