### ISSUE TITLE
Reading list as default page

### ISSUE THREAD

**Issue by jmfayard** [forem/DEV-Android#49]
Hello,
When I am on the desktop, I mostly want to **browse**  the website. 
When I am on the smartphone on the other hand, that's a bad idea IMHO.
I would rather focus on **reading** what is in my reading list.

To enforce this, I would like to have the option to set the first screen to be my reading list.

I'm willing to implement it if you tell me how

**Comment by rt4914** [comment]
Closing this as it is not required now.
