### ISSUE TITLE
Enable Screen Orientation (Landscape) for Android

### ISSUE THREAD

**Issue by KelvnPere** [forem/DEV-Android#62]
**Is your feature request related to a problem? Please describe.**
I was actually on my bed, upside down and I tried viewing an article on my phone on landscape mode and it just didn't work. That was not cool

**Describe the solution you'd like**
I would like to be able to view articles on landscape mode, the same way it is been done on the PWA.

**Describe alternatives you've considered**
The only alternative was using the PWA which works fine.

**Additional context**
I would suggest using a ViewModel Class which would help in configuration change. Because I know this is a pain for Android Developers.

**Comment by rt4914** [comment]
Closing this as it is not required now.
