### ISSUE TITLE
Offline "drawing screen" scrolls on Android app making it hard to draw

### ISSUE THREAD

**Issue by jaeheonshim** [forem/DEV-Android#69]
**Describe the bug**
On the drawing page that the app provides to users who don't currently have internet access, the page scrolls up and down, making it hard to create a decent masterpiece.

**To Reproduce**
1. Turn off wifi on your device
2. Close the app if it was already open
3. Open the app and see the page that says "So, there's good news and bad news"
4. Try to draw.

**Expected behavior**
Making downward and upward movements scrolls the page up and down, distorting the trail left behind by your finger on the page. It would be nice if the page stayed fixed.

**Screenshots**
![issue](https://user-images.githubusercontent.com/35268332/77838086-58cd9300-713e-11ea-836d-bb3afa4aea34.gif)

**Smartphone (please complete the following information):**
 - Device: Google Pixel XL
 - OS: Android
 - Version: 10 (Q)

**Additional context**
I realize this is a minor problem that not many users are bound to experience, but I thought it was an issue worth being mentioned nevertheless.

**Comment by fdoxyz** [comment]
Hello @jaeheonshim, thank you for your report! This is something I can replicate from my end and it happens on both a plain browser from my phone and the app. This will need to be addressed in the web side of DEV ([main repo](https://github.com/thepracticaldev/dev.to)).

To our amazing contributors: issues labeled type: bug are always up for grabs. To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping me here and I'll do my best to follow up as soon as possible.

**Comment by rt4914** [comment]
Closing this as it is not required now.
