### ISSUE TITLE
Project directory restructure (Build Flavors)

### ISSUE THREAD

**Issue by fdocr** [forem/DEV-Android#87]
**Is your feature request related to a problem? Please describe.**

We've recently felt that the current project directory structure is a little too complex for our needs.

Our currently modular project directory (`data`, `buildSrc`, `baseui`, `app`) feels more appropriate for native apps that benefit from Activity/Fragment/ect reuse. In our case we deal with very few moving parts.

**Describe the solution you'd like**

We're open at the moment to contributions where we can simplify our project directory structure. The ideal result is a minimal directory structure where we can easily work on enhancing our main Main Activity & browsing experience with the custom WebViewClient.

The suggested changes that we're looking to see in a PR for this are the following:

- [x] Simplified directory structure
- [x] ~Consider removal of databinding~
- [x] Keep integrations we already have in the project (i.e. [refreshVersions](https://github.com/jmfayard/refreshVersions))
- [ ] Configuration of [Build Flavors](https://developer.android.com/studio/build/build-variants#product-flavors): To reduce contributors friction to spin up their local development and start working on the app we can provide a `google-services.json` dummy file for debug/development ([read more about this](https://github.com/thepracticaldev/DEV-Android#push-notifications))

**Additional context**

PR's for this issue are very welcome. If you have a question or want to suggest alternatives feel free to leave a comment in this issue. We are open to hearing ideas on how to make our directory a minimal version of what we currently have.

**Comment by rt4914** [comment]
Closing this as it is not required now.
