### ISSUE TITLE
Uploading an image to post on android app

### ISSUE THREAD

**Issue by jacobherrington** [forem/DEV-Android#91]
@urielbitton commented on [Mon Jun 29 2020](https://github.com/thepracticaldev/dev.to/issues/8984)

The bug occurs when attempting to upload an image to a post from an android mobile phone on the dev.to app. The image fails to upload, and the page redirects to the home page. Upon visiting the write a post page again, the image hasn't uploaded and another attempt to upload an image results in the same result.

**To Reproduce**

**Expected behavior**
The page should produce an image link that is added to the post upon clicking upload image

**Screenshots**

Not really anything to see.

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy s10
- OS: android 10
- Browser: dev app
- Version: latest version of app

**Comment by jacobherrington** [comment]
@urielbitton Do you mind adding some additional context to this issue? It'd be helpful if you could include the model of device you're using and Android version.

**Comment by fdoxyz** [comment]
I wasn't able to reproduce locally with Android 9 on Galaxy S8. It would be very useful to get more info con device model, OS version and app version.

![image-test3](https://user-images.githubusercontent.com/6045239/86036482-2d876800-b9fb-11ea-86c6-09bd7e5c2f22.gif)

**Comment by urielbitton** [comment]
I believe I specified the galaxy s10 on Android 10. Have you tried on that phone?

**Comment by urielbitton** [comment]
The context is the same that i see in your video. Try it with the phone i specified.

**Comment by urielbitton** [comment]
I see now that the majority of my issue wasn't recorded. I do not understand why.

**Comment by urielbitton** [comment]
Ill try that again.

Bug:

The bug occurs when attempting to upload an image to a post from an android mobile phone on the dev.to app. The image fails to upload, and the page redirects to the home page. Upon visiting the write a post page again, the image hasn't uploaded and another attempt to upload an image results in the same result.

Device: samsung galaxy s10 
OS: Android 10
App: android app, latest version

**Comment by fdoxyz** [comment]
Thank you for the follow up @urielbitton! I'll take a look again soon and see if I'm able to find the cause of the problem

**Comment by rt4914** [comment]
Image is getting added on Forem app.
