### ISSUE TITLE
Link highlighted

### ISSUE THREAD

**Issue by schmelto** [forem/DEV-Android#97]
**Describe the bug**
Through scrolling the news feed done links change there color without really clicking on them. 

**To Reproduce**
1. Go to news feed
2. Scroll down 
3. Taping on link through scrolling (not enter) 

**Expected behavior**
Heighlght after kicking and entering the link. 

**Smartphone:**
 - Device: Huawei P10
 - OS: Android 
 - Version: 9

**Comment by fdoxyz** [comment]
This is a visual enhancement that could definitely be added to the App. However, this is the general way links behave in the browser as well, so the solution lives somewhere between the web app and here.

If we can find some CSS patch to apply to make sure the links don't get highlighted when scrolling it would be a great addition. A posssible way to do this is:

```js
var node = document.createElement('style');
node.type = 'text/css';
node.innerHTML = '<CSS_PATCH>';
document.head.appendChild(node);
```

The JS suggestion above could be manually evaluated (injecting the CSS patch) in the WebView to avoid highlighting links during the normal scroll with the finger. At a first glance this mainly affects links in the feed that are anchor tags nested under a `div` with the `crayons-story__title` class.
